### ISSUE TITLE
Update the https://awards.sigsoft.org/CAPS/ page

### ISSUE THREAD

**Issue by nanniu** [acmsigsoft/www.sigsoft.org#28]
Hello,

I'm the SIGSOFT CAPS coordinator and would like to request the update for the https://awards.sigsoft.org/CAPS/ page since we have been using other channels to manage CAPS for the past couple of years. My request is to keep the 'SIGSOFT CAPS Application' at the top and to remove everything else currently on the page. We'll then provide the link and important dates to specific CAPS for different conferences, e.g., MODELS'22, ASE'22, and ESEC/FSE'22.

These links will be created in the next few days & I'll keep everybody posted.

Thanks,
Nan

**Comment by tzimmermsr** [comment]
Hi Nan,

Going forward, I'd like to deprecate the awards.sigsoft.org page completely.

Instead , we should update this page (which also has the links to the old application form):
https://www.sigsoft.org/resources/caps.html/

The source code is here: https://github.com/acmsigsoft/www.sigsoft.org/blob/master/resources/caps.html

How about we (1) remove individual links to the forms and (2) add a section with links to application forms to the top.

Thanks,
Tom


From: Nan Niu ***@***.***>
Sent: Monday, August 15, 2022 1:03 PM
To: acmsigsoft/www.sigsoft.org ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acmsigsoft/www.sigsoft.org] Update the https://awards.sigsoft.org/CAPS/ page (Issue #28)


Hello,

I'm the SIGSOFT CAPS coordinator and would like to request the update for the https://awards.sigsoft.org/CAPS/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fawards.sigsoft.org%2FCAPS%2F&data=05%7C01%7Ctzimmer%40microsoft.com%7Cbb44492b84da4cd89db508da7ef9215e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637961905719867172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3II74jnIkQWdCa4iFX9waHqz5JhzCk%2BxOJ4J1jRYKVE%3D&reserved=0> page since we have been using other channels to manage CAPS for the past couple of years. My request is to keep the 'SIGSOFT CAPS Application' at the top and to remove everything else currently on the page. We'll then provide the link and important dates to specific CAPS for different conferences, e.g., MODELS'22, ASE'22, and ESEC/FSE'22.

These links will be created in the next few days & I'll keep everybody posted.

Thanks,
Nan

-

**Comment by raux** [comment]
Hi all,

Once all the changes are made, I will port all the changes to the new website. My plan is to create a page dedicated to SIGSOFT CAPS.

Cheers,

Raula

**Comment by nanniu** [comment]
Thank you both! I'll provide specific modifications to the https://www.sigsoft.org/resources/caps.html/ . Also, @tzimmermsr Do you mean to deprecate https://awards.sigsoft.org/CAPS/ (and if so, I agree)?

**Comment by raux** [comment]
Hi Nan,
(cc. Tom)

We are now moving to a new beta sigsoft website at https://acmsigsoft.github.io/

Hence, I created a sample page for CAPS
https://acmsigsoft.github.io/docs/Website/CAPS/

Since the new website is built on Hugo, we use markdown language for updating. Which is below. 

https://github.com/acmsigsoft/acmsigsoft.github.io/blob/main/content/docs/Website/CAPS.md

Depending on your markdown experience, please clarify what content you would like moved to this new page, or send a PR, and I can update this for you.

@Tom - Do add comments if needed. 

Cheers,

Raula

**Comment by nanniu** [comment]
Thanks, Raula! I'd like to update https://awards.sigsoft.org/CAPS/ to the following page (I'm copying the HTML source here, if desired, you can create a new HTML file and view the content):


<h1>SIGSOFT Travel Support and Childcare Assistance at Conferences - CAPS</h1>
<p>CAPS provides support for students and professionals to attend the conferences and events sponsored by ACM SIGSOFT. Currently, CAPS applications are open for:</p>

<ul>
 <li><a href="https://conf.researchr.org/home/models-2022">MODELS 2022:</a> CAPS application deadline: September 9, 2022. To apply: fill your application at <a href="https://survey.alchemer.com/s3/6986681/SIGSOFT-CAPS-Support-for-MODELS-2022">this link</a>.</li>
 <li><a href="">(more to be announced)</a></li>
</ul>

<p>If you have any questions about this program please contact <a href="mailto:sigsoft_caps@acm.org?subject=SIGSOFT CAPS question">SIGSOFT CAPS Coordinator</a>.</p>

The page https://awards.sigsoft.org/CAPS/ shall be deprecated as soon as possible, as we're using it at all. Applicants who access the current https://awards.sigsoft.org/CAPS/ are confused and keep emailing us the same questions.

@tzimmermsr : Let me know if you're good with my above request.

@raux : I understand that you're building up a new and cool version of our site, but please take care of my above request first :) I'll enrich the CAPS page with more descriptions later.

Thanks,
Nan

**Comment by raux** [comment]
@nanniu I think the best way then is to first clone the project, then make changes to the source code page.
https://github.com/acmsigsoft/www.sigsoft.org/blob/master/resources/caps.html

Then send me a PR, so I can integrate into the website. 
Else, I can just make the updates as mentioned in the prior comment.

Raula

**Comment by nanniu** [comment]
Thanks @raux I just made a pull request. Please review and let me know if you have any questions. I really hope that https://www.sigsoft.org/resources/caps.html can be replaced with the new file that I proposed ASAP.

**Comment by raux** [comment]
@nanniu please have a look at 
https://www.sigsoft.org/resources/caps.html

Let me know if something is wrong or missing.
Raula

**Comment by nanniu** [comment]
The new page looks good -- thank yo so much @raux ! I'm closing this issue now & will request further updates later. Have a great weekend!
