### ISSUE TITLE
Folder request to upload CAPS reports

### ISSUE THREAD

**Issue by nanniu** [acmsigsoft/www.sigsoft.org#43]
Hello @raux and @tzimmermsr 

I'm not sure if I've raised this issue before, but I'd like to request a folder structure to upload the CAPS reports written by awardees (mostly, students). I'd like to link these reports to the page https://www.sigsoft.org/resources/caps.html For example, 'ASE 2022' received two students' reports in PDF format. I'd like to be able to upload these PDF reports to a folder (e.g., named CAPS_Reports/ASE_2022) and then published them on the page.

Can you help?

Thanks,
Nan

**Comment by raux** [comment]
Hi Nan,

We are currently in transition to a new website. We can accomodate this new feature, so I am hoping to provide you this in a few weeks hopefully. 

Raula

**Comment by nanniu** [comment]
Thank you @raux ! I look forward to the updates.

Best,
Nan

**Comment by raux** [comment]
@nanniu @tzimmermsr Hi Nan,

Sorry it has been a very long minute, but finally got to creating the new website, which we have now launched.

the repo for the CAPS section is here

https://github.com/acmsigsoft/acmsigsoft.github.io/tree/main/content/CAPS

You can now edit the file below in md style. https://github.com/acmsigsoft/acmsigsoft.github.io/blob/main/content/CAPS/CAPSMAIN.md

Since you requested a folder structure to upload the CAPS reports, I have created a folder in the repo 

https://github.com/acmsigsoft/acmsigsoft.github.io/tree/main/static/CAPS

Here you can put reports. To add the report to the md file, you simply need to add the following markdown pattern (replace xx with the file name).

- [Report xxx ](/CAPS/xxx.pdf)


Hope this helps. 

Raula
